-- Migration v8: Loan Insight Table
-- Pre-generated Loan Insight storage for CorporateDetailPage
-- Generated at Worker INSIGHT pipeline stage

-- ============================================================
-- 1. rkyc_loan_insight 테이블 생성
-- ============================================================

CREATE TABLE IF NOT EXISTS rkyc_loan_insight (
    -- PK
    insight_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- FK: 기업
    corp_id VARCHAR(20) NOT NULL REFERENCES corp(corp_id) ON DELETE CASCADE,

    -- Stance (종합 판단)
    stance_level VARCHAR(20) NOT NULL DEFAULT 'STABLE',  -- CAUTION, MONITORING, STABLE, POSITIVE
    stance_label VARCHAR(50) NOT NULL DEFAULT '중립/안정적',
    stance_color VARCHAR(20) NOT NULL DEFAULT 'green',

    -- Narrative (종합 소견)
    narrative TEXT NOT NULL DEFAULT '',

    -- Key Risks (핵심 리스크 요인)
    key_risks JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Mitigating Factors (리스크 상쇄/기회 요인)
    mitigating_factors JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Action Items (심사역 확인 체크리스트)
    action_items JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Generation metadata
    signal_count INT NOT NULL DEFAULT 0,           -- 분석에 사용된 시그널 수
    risk_count INT NOT NULL DEFAULT 0,             -- Risk 시그널 수
    opportunity_count INT NOT NULL DEFAULT 0,       -- Opportunity 시그널 수

    -- LLM metadata
    generation_model VARCHAR(100),                  -- 생성에 사용된 모델 (claude-opus-4-5, gpt-5.2-pro 등)
    generation_prompt_version VARCHAR(20),          -- 프롬프트 버전
    is_fallback BOOLEAN NOT NULL DEFAULT FALSE,     -- Rule-based fallback 여부

    -- Timestamps
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- 생성 시점
    expires_at TIMESTAMPTZ,                           -- 만료 시점 (TTL)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. 인덱스 생성
-- ============================================================

-- corp_id로 조회 (가장 빈번)
CREATE INDEX IF NOT EXISTS idx_loan_insight_corp_id
    ON rkyc_loan_insight(corp_id);

-- corp_id + 최신 생성일 (최신 insight 조회)
CREATE INDEX IF NOT EXISTS idx_loan_insight_corp_generated
    ON rkyc_loan_insight(corp_id, generated_at DESC);

-- stance_level별 조회 (대시보드용)
CREATE INDEX IF NOT EXISTS idx_loan_insight_stance
    ON rkyc_loan_insight(stance_level);

-- 만료 데이터 정리용
CREATE INDEX IF NOT EXISTS idx_loan_insight_expires
    ON rkyc_loan_insight(expires_at)
    WHERE expires_at IS NOT NULL;

-- ============================================================
-- 3. UNIQUE 제약 (corp_id당 1개만 유지)
-- ============================================================

-- 기업당 최신 1개만 유지하려면 UNIQUE 제약 추가
-- 또는 UPDATE/INSERT ON CONFLICT 사용
CREATE UNIQUE INDEX IF NOT EXISTS idx_loan_insight_corp_unique
    ON rkyc_loan_insight(corp_id);

-- ============================================================
-- 4. updated_at 자동 갱신 트리거
-- ============================================================

CREATE OR REPLACE FUNCTION update_loan_insight_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_loan_insight_updated_at ON rkyc_loan_insight;
CREATE TRIGGER trg_loan_insight_updated_at
    BEFORE UPDATE ON rkyc_loan_insight
    FOR EACH ROW
    EXECUTE FUNCTION update_loan_insight_updated_at();

-- ============================================================
-- 5. 코멘트
-- ============================================================

COMMENT ON TABLE rkyc_loan_insight IS 'Pre-generated Loan Insight for CorporateDetailPage. Generated at Worker INSIGHT pipeline stage.';
COMMENT ON COLUMN rkyc_loan_insight.stance_level IS 'CAUTION, MONITORING, STABLE, POSITIVE';
COMMENT ON COLUMN rkyc_loan_insight.is_fallback IS 'True if generated by rule-based fallback instead of LLM';
