-- Test Seed Data for Corp Profile (PRD v1.2)
-- Run after migration_v7_corp_profile.sql

-- 엠케이전자 (8001-3719240) - 반도체 부품
INSERT INTO rkyc_corp_profile (
    corp_id,
    business_summary,
    revenue_krw,
    export_ratio_pct,
    ceo_name,
    employee_count,
    founded_year,
    headquarters,
    executives,
    industry_overview,
    business_model,
    financial_history,
    country_exposure,
    key_materials,
    key_customers,
    overseas_operations,
    competitors,
    macro_factors,
    supply_chain,
    overseas_business,
    shareholders,
    consensus_metadata,
    profile_confidence,
    field_confidences,
    source_urls,
    is_fallback,
    search_failed,
    validation_warnings,
    status,
    fetched_at,
    expires_at
) VALUES (
    '8001-3719240',
    '엠케이전자는 반도체 부품 전문 기업으로, 메모리 반도체 테스트 소켓과 PCB 어셈블리 제품을 생산합니다. 국내외 주요 반도체 기업에 부품을 공급하며, 수출 비중이 높은 글로벌 기업입니다.',
    150000000000,  -- 1500억원
    62,
    '박민수',
    1250,
    1998,
    '경기도 화성시 동탄산업단지',
    '[{"name": "박민수", "position": "대표이사", "tenure_years": 12}, {"name": "김영호", "position": "부사장", "tenure_years": 8}]'::jsonb,
    '반도체 부품 산업은 글로벌 반도체 수요 증가와 함께 성장세를 유지하고 있으며, 특히 AI 반도체 수요 증가가 시장을 견인하고 있습니다.',
    'B2B 부품 공급 (OEM)',
    '[{"year": 2025, "revenue_krw": 150000000000, "operating_profit_krw": 18000000000, "net_profit_krw": 14000000000}, {"year": 2024, "revenue_krw": 135000000000, "operating_profit_krw": 15000000000, "net_profit_krw": 11500000000}, {"year": 2023, "revenue_krw": 120000000000, "operating_profit_krw": 12000000000, "net_profit_krw": 9000000000}]'::jsonb,
    '{"중국": 35, "미국": 20, "일본": 7}'::jsonb,
    ARRAY['실리콘 웨이퍼', 'PCB 원자재', '금속 리드프레임'],
    ARRAY['삼성전자', 'SK하이닉스', '마이크론'],
    ARRAY['베트남 하노이 공장'],
    '[{"name": "리노공업", "market_share_pct": 15, "relationship": "DIRECT"}, {"name": "ISC", "market_share_pct": 12, "relationship": "DIRECT"}]'::jsonb,
    '[{"factor": "AI 반도체 수요 증가", "impact": "POSITIVE", "description": "ChatGPT 등 AI 서비스 확산으로 데이터센터 반도체 수요 급증"}, {"factor": "미중 반도체 갈등", "impact": "NEGATIVE", "description": "중국 수출 규제로 인한 매출 영향 가능성"}, {"factor": "원자재 가격 상승", "impact": "NEGATIVE", "description": "실리콘, 구리 등 원자재 가격 상승"}]'::jsonb,
    '{"key_suppliers": ["신에츠화학", "스미토모금속", "SKC"], "supplier_countries": {"일본": 45, "한국": 35, "대만": 20}, "single_source_risk": ["실리콘 웨이퍼 (신에츠화학)"], "material_import_ratio_pct": 65}'::jsonb,
    '{"subsidiaries": [{"name": "MK Electronics Vietnam", "country": "베트남", "business_type": "제조", "ownership_pct": 100}], "manufacturing_countries": ["베트남", "한국"]}'::jsonb,
    '[{"name": "박민수", "ownership_pct": 28.5, "is_largest": true, "relationship": "FOUNDER"}, {"name": "국민연금", "ownership_pct": 8.2, "relationship": "INSTITUTION"}, {"name": "외국인", "ownership_pct": 15.3, "relationship": "FOREIGN"}]'::jsonb,
    '{"consensus_at": "2026-01-20T10:00:00Z", "perplexity_success": true, "gemini_success": true, "claude_success": false, "total_fields": 19, "matched_fields": 15, "discrepancy_fields": 2, "enriched_fields": 2, "overall_confidence": "HIGH", "fallback_layer": 1, "retry_count": 0, "error_messages": []}'::jsonb,
    'HIGH',
    '{"revenue_krw": "HIGH", "export_ratio_pct": "HIGH", "country_exposure": "MED", "supply_chain": "MED"}'::jsonb,
    ARRAY['https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250115000123', 'https://www.mk-elec.co.kr/ir/', 'https://news.einfomax.co.kr/news/articleView.html?idxno=4567890'],
    false,
    false,
    ARRAY[]::text[],
    'ACTIVE',
    NOW(),
    NOW() + INTERVAL '7 days'
) ON CONFLICT (corp_id) DO UPDATE SET
    business_summary = EXCLUDED.business_summary,
    revenue_krw = EXCLUDED.revenue_krw,
    export_ratio_pct = EXCLUDED.export_ratio_pct,
    ceo_name = EXCLUDED.ceo_name,
    employee_count = EXCLUDED.employee_count,
    supply_chain = EXCLUDED.supply_chain,
    overseas_business = EXCLUDED.overseas_business,
    consensus_metadata = EXCLUDED.consensus_metadata,
    profile_confidence = EXCLUDED.profile_confidence,
    updated_at = NOW();

-- 동부건설 (8000-7647330) - 건설업
INSERT INTO rkyc_corp_profile (
    corp_id,
    business_summary,
    revenue_krw,
    export_ratio_pct,
    ceo_name,
    employee_count,
    founded_year,
    headquarters,
    industry_overview,
    business_model,
    country_exposure,
    key_customers,
    competitors,
    macro_factors,
    supply_chain,
    shareholders,
    consensus_metadata,
    profile_confidence,
    source_urls,
    is_fallback,
    status,
    fetched_at,
    expires_at
) VALUES (
    '8000-7647330',
    '동부건설은 주거용 아파트 및 상업시설 건설을 전문으로 하는 종합건설사입니다. 최근 부동산 시장 침체로 신규 수주가 감소하였으나, 재건축/재개발 사업에서 강점을 보이고 있습니다.',
    520000000000,  -- 5200억원
    0,
    '이동훈',
    2100,
    1982,
    '서울특별시 강남구',
    '국내 건설업은 금리 상승과 부동산 규제로 인해 주택 시장 침체가 지속되고 있으나, 인프라 및 재건축 시장은 성장세를 유지하고 있습니다.',
    '수주형 건설 (주거/상업)',
    '{}'::jsonb,
    ARRAY['LH', '서울주택도시공사', '재건축조합'],
    '[{"name": "대우건설", "relationship": "DIRECT"}, {"name": "현대건설", "relationship": "DIRECT"}]'::jsonb,
    '[{"factor": "금리 상승", "impact": "NEGATIVE", "description": "PF 대출 금리 상승으로 사업성 악화"}, {"factor": "재건축 규제 완화", "impact": "POSITIVE", "description": "정부 재건축 규제 완화 정책"}]'::jsonb,
    '{"key_suppliers": ["포스코건설", "한국철강"], "supplier_countries": {"한국": 95, "중국": 5}, "single_source_risk": [], "material_import_ratio_pct": 5}'::jsonb,
    '[{"name": "이동훈", "ownership_pct": 35.0, "is_largest": true, "relationship": "FOUNDER"}, {"name": "우리은행", "ownership_pct": 12.0, "relationship": "INSTITUTION"}]'::jsonb,
    '{"consensus_at": "2026-01-20T10:30:00Z", "perplexity_success": true, "gemini_success": true, "claude_success": false, "total_fields": 15, "matched_fields": 12, "discrepancy_fields": 1, "enriched_fields": 2, "overall_confidence": "MED", "fallback_layer": 1, "retry_count": 0, "error_messages": []}'::jsonb,
    'MED',
    ARRAY['https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20250115000456'],
    false,
    'ACTIVE',
    NOW(),
    NOW() + INTERVAL '7 days'
) ON CONFLICT (corp_id) DO UPDATE SET
    business_summary = EXCLUDED.business_summary,
    updated_at = NOW();

-- Verify data
SELECT corp_id, business_summary, profile_confidence,
       supply_chain->>'key_suppliers' as suppliers,
       consensus_metadata->>'fallback_layer' as fallback_layer
FROM rkyc_corp_profile;
